// Copyright (c) 2021 Runeterra Team
// Chris Ohk, Dongyeon Park, Seungwon Seo
// We are making my contributions/submissions to this project solely in our
// personal capacity and are not conveying any rights to any intellectual
// property of any third parties.

#ifndef RUNETERRA_DECK_CODE_HPP
#define RUNETERRA_DECK_CODE_HPP

#include <string>

#include <Runeterra/Decks/Deck.hpp>

namespace Runeterra
{
//!
//! \brief DeckCode class.
//!
//! This class encodes/decodes Legend of Runeterra decks to/from simple strings.
//!
class DeckCode
{
 public:
    //! Decodes a deck code and returns the deck that contains some cards.
    //! \param deckCode The deck code generated by Legends of Runeterra.
    //! \return The decoded deck that contains card information.
    static Deck Decode(const std::string& deckCode);

    //! Decodes a group and returns a list of matched cards.
    static void DecodeGroup(std::vector<uint8_t>* cardStream, Deck& deck);
};
}  // namespace Runeterra

#endif  // RUNETERRA_DECK_CODE_HPP