// Copyright (c) 2021 Runeterra Team
// Chris Ohk, Seokmin Hong, Woojin Kim
// We are making my contributions/submissions to this project solely in our
// personal capacity and are not conveying any rights to any intellectual
// property of any third parties.

#ifndef RUNETERRA_DECK_CODE_HELPERS_HPP
#define RUNETERRA_DECK_CODE_HELPERS_HPP

#include <string>
#include <vector>

namespace Runeterra::DeckCode
{
//! Decodes a deck code and returns the deck that contains some cards.
//! \param deckCode The deck code generated by Legends of Runeterra.
//! \return A list of cards that is decoded.
std::vector<std::string> Decode(const std::string& deckCode);
}  // namespace Runeterra::DeckCode

#endif  // RUNETERRA_DECK_CODE_HELPERS_HPP
